### ISSUE TITLE
"configure" function does not work properly.

### ISSUE THREAD

**Issue by Garitron** [paeaetech/paeae#2]
The function does not return "true" because the readByte() call returns junk.  It's not clear to me that the configuration is being properly set, since the junk (0x18) does not indicate a proper response (which should be 0x01 in my case).  In fact, the upper nibble of the return should be 0 for a completed configuration request (0xd2) no matter what configuration is requested.

The "configure" function can be made to work properly by including an "end();" function call after the two "write" functions and before the "return".

73, Garitron (aka Gary Fariss)

**Comment by sivu** [comment]
fixed
